Include a clientid in mqtt commands
ned-kelly/docker-voltronic-homeassistant pull request #45
Opened 2021-06-03 13:28 UTC by RSd108

A configurable clientid is added to mqtt config

This fixes  #42  and #43

2021-06-03 14:00 UTC, TaariqSurtee approved these changes

2021-06-03 14:00 UTC, TaariqSurtee commented
It looks correct. I will have to test it.

2021-06-06 12:40 UTC, RHeynsZa requested changes

2021-06-06 12:40 UTC, RHeynsZa commented on sources/inverter-mqtt/mqtt-push.sh
> +	MQTT_CLIENTID=`cat /etc/inverter/mqtt.json | jq '.clientid' -r`
This is a tab, but the file uses spaces

2021-06-06 12:40 UTC, RHeynsZa commented on config/mqtt.json
> +	"clientid": "voltronic_bd8041d0cdf131a6ba4e5b3360b8bc5a",
tab vs spaces

2021-06-06 18:05 UTC, RHeynsZa commented
Tested this, still not sending mqtt messages

2021-06-07 13:24 UTC, RHeynsZa commented
> It looks correct. I will have to test it.

I tested on my side, this works, but seems like the underscore had some issues for my broker, so i just set the client to `inverter`

2021-10-06 12:36 UTC, merged